# -*- coding: utf-8 -*-
import _thread

# Form implementation generated from reading ui file 'front_panel.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from control import Oscilloscope
import threading
import time


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(805, 600)
        MainWindow.setMinimumSize(QtCore.QSize(805, 600))
        MainWindow.setMaximumSize(QtCore.QSize(805, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 781, 91))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayoutTop = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayoutTop.setContentsMargins(0, 0, 0, 0)
        self.verticalLayoutTop.setObjectName("verticalLayoutTop")
        self.labelPosition_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelPosition_2.setFont(font)
        self.labelPosition_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.labelPosition_2.setFrameShape(QtWidgets.QFrame.Box)
        self.labelPosition_2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPosition_2.setObjectName("labelPosition_2")
        self.verticalLayoutTop.addWidget(self.labelPosition_2)
        self.spinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(4)
        self.spinBox.setObjectName("spinBox")
        self.verticalLayoutTop.addWidget(self.spinBox)
        self.pushButtonAutoscale = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButtonAutoscale.setObjectName("pushButtonAutoscale")
        self.verticalLayoutTop.addWidget(self.pushButtonAutoscale)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 440, 171, 131))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.verticalLayoutWidget_2.setFont(font)
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayoutBottomFarLeft = QtWidgets.QVBoxLayout(
            self.verticalLayoutWidget_2
        )
        self.verticalLayoutBottomFarLeft.setContentsMargins(0, 0, 0, 0)
        self.verticalLayoutBottomFarLeft.setObjectName("verticalLayoutBottomFarLeft")
        self.labelVerticalOffsetValue = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelVerticalOffsetValue.setFont(font)
        self.labelVerticalOffsetValue.setFrameShape(QtWidgets.QFrame.Box)
        self.labelVerticalOffsetValue.setFrameShadow(QtWidgets.QFrame.Plain)
        self.labelVerticalOffsetValue.setAlignment(QtCore.Qt.AlignCenter)
        self.labelVerticalOffsetValue.setObjectName("labelVerticalOffsetValue")
        self.verticalLayoutBottomFarLeft.addWidget(self.labelVerticalOffsetValue)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(210, 440, 171, 131))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.verticalLayoutWidget_3.setFont(font)
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayoutBottomCenterLeft = QtWidgets.QVBoxLayout(
            self.verticalLayoutWidget_3
        )
        self.verticalLayoutBottomCenterLeft.setContentsMargins(0, 0, 0, 0)
        self.verticalLayoutBottomCenterLeft.setObjectName(
            "verticalLayoutBottomCenterLeft"
        )
        self.labelHorizontalOffsetValue = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelHorizontalOffsetValue.setFont(font)
        self.labelHorizontalOffsetValue.setFrameShape(QtWidgets.QFrame.Box)
        self.labelHorizontalOffsetValue.setFrameShadow(QtWidgets.QFrame.Plain)
        self.labelHorizontalOffsetValue.setAlignment(QtCore.Qt.AlignCenter)
        self.labelHorizontalOffsetValue.setObjectName("labelHorizontalOffsetValue")
        self.verticalLayoutBottomCenterLeft.addWidget(self.labelHorizontalOffsetValue)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(420, 440, 173, 131))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.verticalLayoutWidget_4.setFont(font)
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayoutBottomCenterRight = QtWidgets.QVBoxLayout(
            self.verticalLayoutWidget_4
        )
        self.verticalLayoutBottomCenterRight.setContentsMargins(0, 0, 0, 0)
        self.verticalLayoutBottomCenterRight.setObjectName(
            "verticalLayoutBottomCenterRight"
        )
        self.labelVerticalAmplificationValue = QtWidgets.QLabel(
            self.verticalLayoutWidget_4
        )
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelVerticalAmplificationValue.setFont(font)
        self.labelVerticalAmplificationValue.setFrameShape(QtWidgets.QFrame.Box)
        self.labelVerticalAmplificationValue.setFrameShadow(QtWidgets.QFrame.Plain)
        self.labelVerticalAmplificationValue.setAlignment(QtCore.Qt.AlignCenter)
        self.labelVerticalAmplificationValue.setObjectName(
            "labelVerticalAmplificationValue"
        )
        self.verticalLayoutBottomCenterRight.addWidget(
            self.labelVerticalAmplificationValue
        )
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(620, 440, 171, 131))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.verticalLayoutWidget_5.setFont(font)
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayoutBottomFarRight = QtWidgets.QVBoxLayout(
            self.verticalLayoutWidget_5
        )
        self.verticalLayoutBottomFarRight.setContentsMargins(0, 0, 0, 0)
        self.verticalLayoutBottomFarRight.setObjectName("verticalLayoutBottomFarRight")
        self.labelHorizontalAmplificationValue = QtWidgets.QLabel(
            self.verticalLayoutWidget_5
        )
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelHorizontalAmplificationValue.setFont(font)
        self.labelHorizontalAmplificationValue.setFrameShape(QtWidgets.QFrame.Box)
        self.labelHorizontalAmplificationValue.setFrameShadow(QtWidgets.QFrame.Plain)
        self.labelHorizontalAmplificationValue.setAlignment(QtCore.Qt.AlignCenter)
        self.labelHorizontalAmplificationValue.setObjectName(
            "labelHorizontalAmplificationValue"
        )
        self.verticalLayoutBottomFarRight.addWidget(
            self.labelHorizontalAmplificationValue
        )
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 110, 781, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelPosition = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelPosition.setFont(font)
        self.labelPosition.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.labelPosition.setFrameShape(QtWidgets.QFrame.Box)
        self.labelPosition.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPosition.setObjectName("labelPosition")
        self.horizontalLayout_2.addWidget(self.labelPosition)
        self.labelAmplification = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelAmplification.setFont(font)
        self.labelAmplification.setFrameShape(QtWidgets.QFrame.Box)
        self.labelAmplification.setAlignment(QtCore.Qt.AlignCenter)
        self.labelAmplification.setObjectName("labelAmplification")
        self.horizontalLayout_2.addWidget(self.labelAmplification)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 297, 171, 131))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 160, 171, 131))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(420, 297, 171, 131))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(420, 160, 171, 131))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(10, 140, 780, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(210, 297, 171, 131))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(210, 160, 171, 131))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(620, 297, 171, 131))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(620, 160, 171, 131))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.scope = Oscilloscope("100")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        #thread.start_new_thread(self.refresh, (10,))
        #x = threading.Thread(target=self.refresh, args=(1,), daemon=True)
        #x.start()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(
            _translate("MainWindow", "SIX SIGMA pyQt-scope-control")
        )
        self.labelPosition_2.setText(_translate("MainWindow", "Kanał"))
        self.pushButtonAutoscale.setText(
            _translate("MainWindow", "Automatyczne ustawienie")
        )
        self.labelVerticalOffsetValue.setText(
            _translate(
                "MainWindow",
                "<html><head/><body><p><span style=\" font-family:'sans-serif'; color:#202122; background-color:#f8f9fa;\">↕</span></p><p><span style=\" font-family:'sans-serif'; color:#202122; background-color:#f8f9fa;\">Wartość: </span></p></body></html>",
            )
        )
        self.labelHorizontalOffsetValue.setText(
            _translate(
                "MainWindow",
                "<html><head/><body><p><span style=\" font-family:'sans-serif'; color:#202122; background-color:#f8f9fa;\">↔</span></p><p><span style=\" font-family:'sans-serif'; color:#202122; background-color:#f8f9fa;\">Wartość: </span></p></body></html>",
            )
        )
        self.labelVerticalAmplificationValue.setText(
            _translate(
                "MainWindow",
                "<html><head/><body><p><span style=\" font-family:'sans-serif'; color:#202122; background-color:#f8f9fa;\">↕</span></p><p><span style=\" font-family:'sans-serif'; color:#202122; background-color:#f8f9fa;\">Wartość: </span></p></body></html>",
            )
        )
        self.labelHorizontalAmplificationValue.setText(
            _translate(
                "MainWindow",
                '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n'
                '<html><head><meta name="qrichtext" content="1" /><style type="text/css">\n'
                "p, li { white-space: pre-wrap; }\n"
                "</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
                '<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'sans-serif\'; color:#202122; background-color:#f8f9fa;">↔</span></p>\n'
                '<p style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'sans-serif\'; color:#202122; background-color:#f8f9fa;">Wartość: </span></p></body></html>',
            )
        )
        self.labelPosition.setText(_translate("MainWindow", "Pozycja"))
        self.labelAmplification.setText(_translate("MainWindow", "Wzmocnienie"))
        self.pushButton.setText(_translate("MainWindow", "↓"))
        self.pushButton_2.setText(_translate("MainWindow", "↑"))
        self.pushButton_3.setText(_translate("MainWindow", "↓"))
        self.pushButton_4.setText(_translate("MainWindow", "↑"))
        self.pushButton_5.setText(_translate("MainWindow", "→"))
        self.pushButton_6.setText(_translate("MainWindow", "←"))
        self.pushButton_7.setText(_translate("MainWindow", "→"))
        self.pushButton_8.setText(_translate("MainWindow", "←"))

        self.pushButtonAutoscale.clicked.connect(self.scope.autoscale)
        self.pushButton_2.clicked.connect(
            lambda: self.scope.set_vertical_offset("up", self.spinBox.value())
        )
        self.pushButton.clicked.connect(
            lambda: self.scope.set_vertical_offset("down", self.spinBox.value())
        )
        self.pushButton_6.clicked.connect(
            lambda: self.scope.set_horizontal_offset("left")
        )
        self.pushButton_5.clicked.connect(
            lambda: self.scope.set_horizontal_offset("right")
        )
        self.pushButton_4.clicked.connect(
            lambda: self.scope.set_vertical_amplification(
                "up", self.spinBox.value()
            )
        )
        self.pushButton_3.clicked.connect(
            lambda: self.scope.set_vertical_amplification(
                "down", self.spinBox.value()
            )
        )
        self.pushButton_8.clicked.connect(lambda: self.scope.set_timebase("left"))
        self.pushButton_7.clicked.connect(lambda: self.scope.set_timebase("right"))

    # def refresh(self, delay):
    #     while True:
    #         self.pushButtonAutoscale.clicked.connect(self.scope.autoscale)
    #         self.pushButton_2.clicked.connect(
    #             lambda: self.scope.set_vertical_offset("up", self.spinBox.value())
    #         )
    #         self.pushButton.clicked.connect(
    #             lambda: self.scope.set_vertical_offset("down", self.spinBox.value())
    #         )
    #         self.pushButton_6.clicked.connect(
    #             lambda: self.scope.set_horizontal_offset("left")
    #         )
    #         self.pushButton_5.clicked.connect(
    #             lambda: self.scope.set_horizontal_offset("right")
    #         )
    #         self.pushButton_4.clicked.connect(
    #             lambda: self.scope.set_vertical_amplification(
    #                 "up", self.spinBox.value()
    #             )
    #         )
    #         self.pushButton_3.clicked.connect(
    #             lambda: self.scope.set_vertical_amplification(
    #                 "down", self.spinBox.value()
    #             )
    #         )
    #         self.pushButton_8.clicked.connect(lambda: self.scope.set_timebase("left"))
    #         self.pushButton_7.clicked.connect(lambda: self.scope.set_timebase("right"))
    #         print(self.spinBox.value())
    #         time.sleep(delay)

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
